version: '3.8'

services:

  postgres:
    image: postgres:14.1-alpine
    container_name: ts-app-postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=strichati
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local
  pgadmin:
    driver: local